const myData = [
  {
    id: 1,
    titulo: "Velas con esencias. 16 esencias disponibles",
    imagen: "/assets/img/imagen1.jpeg",
    precio: "$7000",
  },
  {
    id: 2,
    titulo: "2",
    imagen: "/assets/img/imagen2.jpeg",
    precio: "$7000",
  },
  {
    id: 3,
    titulo: "Kundalini Clear",
    imagen: "/assets/img/imagen3.jpeg",
    precio: "$7000",
  },
  {
    id: 4,
    titulo: "4",
    imagen: "/assets/img/imagen4.jpeg",
    precio: "$7000",
  },
  {
    id: 5,
    titulo: "5",
    imagen: "/assets/img/imagen5.jpeg",
    precio: "$7000",
  },
  {
    id: 6,
    titulo: "6",
    imagen: "/assets/img/imagen6.jpeg",
    precio: "$7000",
  },
  {
    id: 7,
    titulo: "7",
    imagen: "/assets/img/imagen7.jpeg",
    precio: "$7000",
  },
  {
    id: 8,
    titulo: "8",
    imagen: "/assets/img/imagen8.jpeg",
    precio: "$7000",
  },
  {
    id: 9,
    titulo: "9",
    imagen: "/assets/img/imagen9.jpeg",
    precio: "$7000",
  },
  {
    id: 10,
    titulo: "10",
    imagen: "/assets/img/imagen10.jpeg",
    precio: "$7000",
  },
  {
    id: 11,
    titulo: "11",
    imagen: "/assets/img/imagen11.jpeg",
    precio: "$7000",
  },
  {
    id: 12,
    titulo: "12",
    imagen: "/assets/img/imagen12.jpeg",
    precio: "$9000",
  },
  {
    id: 13,
    titulo: "13",
    imagen: "/assets/img/imagen13.jpeg",
    precio: "$10500",
  },
  {
    id: 14,
    titulo: "14",
    imagen: "/assets/img/imagen14.jpeg",
    precio: "$3500",
  },
  {
    id: 15,
    titulo: "15",
    imagen: "/assets/img/imagen15.jpeg",
    precio: "$12000",
  },
  {
    id: 16,
    titulo: "16",
    imagen: "/assets/img/imagen16.jpeg",
    precio: "$8000",
  },
  {
    id: 17,
    titulo: "17",
    imagen: "/assets/img/imagen17.jpeg",
    precio: "$6000",
  },
];
